# -*- coding: utf-8 -*-
"""Teste - Stremlit - Toledo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16rBJZ0C56ofss-qzrrcHbZsX9F5OdcRL
"""

pip install streamlit-extras

from streamlit_extras.colored_header import colored_header

colored_header(
    label="My New Pretty Colored Header",
    description="This is a description",
    color_name="violet-70",
)