# -*- coding: utf-8 -*-
"""Teste - Dash - Toledo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1luedb6bR27woo13wgnX55fjD4AN43eHm
"""

# Instale a biblioteca Dash

import dash
import dash_core_components as dcc
import dash_html_components as html

import pandas as pd
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("data.csv")

# Crie os componentes de visualização de dados
graph = dcc.Graph(
    id="graph",
    data={"x": data["x"], "y": data["y"]},
    layout={"title": "Gráfico de linha"},
)
table = dcc.Table(
    data=data.to_dict("records"),
    columns=[{"id": col, "name": col} for col in data.columns],
)

# Conecte os componentes de visualização de dados aos dados
graph.update_data(x=data["x"], y=data["y"])

# Exiba o dashboard no navegador
app = dash.Dash(__name__)
app.layout = html.Div(children=[graph, table])

app.run_server(debug=True)
